### ISSUE TITLE
Villager spawning

### ISSUE THREAD

**Issue by recon88** [IntellectualCrafters/PlotSquared#131]
I set the whole spawning section to false but people are still able to spawn Villager with eggs.
Can we get that added please? :)
```
     event:
      spawn:
        breeding: false
        egg: false
        custom: false
```
