### ISSUE TITLE
Worlds not working 

### ISSUE THREAD

**Issue by flamboo** [IntellectualCrafters/PlotSquared#225]
Hi, After about A week My plot worlds stop working.

here is my config. 
```yml
version: 2.8.11
schematics:
  save_path: /plugins/PlotSquared/schematics
uuid:
  read-from-disk: false
claim:
  max-auto-area: 1
max_plots: 127
console:
  color: true
teleport:
  on_login: false
  delay: 0
debug: true
clusters:
  enabled: true
auto_update: false
plotme-convert:
  enabled: true
kill_road_mobs: true
confirmation:
  unlink: true
  delete: true
  clear: true
metrics: true
cache:
  permissions: false
plotme-alias: false
clear:
  auto:
    enabled: false
    days: 365
  check-disk: false
  'on':
    ban: false
mob_pathfinding: true
worldedit:
  require-selection-in-mask: true
titles: true
UUID:
  offline: false
worlds:
  newplots:
    plot:
      height: 64
      size: 31
      filling:
      - '1:0'
      floor:
      - '2:0'
      bedrock: true
      biome: FOREST
      create_signs: true
      auto_merge: false
    wall:
      block: '44:0'
      block_claimed: '44:7'
      filling: '1:0'
      height: 64
    road:
      width: 7
      height: 64
      block: '155:0'
    event:
      spawn:
        breeding: false
        egg: false
        custom: true
      pvp: false
      pve: false
    economy:
      use: false
      prices:
        claim: 100.0
        sell: 75.0
        merge: 100.0
    world:
      border: false
    schematic:
      file: 'null'
      on_claim: false
      specify_on_claim: false
    chat:
      enabled: false
    flags: {}
    natural_mob_spawning: false
```

there are no erros logged in console.
